# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from spencer_control_msgs/SystemStatus.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class SystemStatus(genpy.Message):
  _md5sum = "f87947cd4c1622efddd24842cc92be75"
  _type = "spencer_control_msgs/SystemStatus"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
bool software_emergency_stop    # True if software emergency stop has been activated; usually causes quick-stop relay to be triggered.
bool hardware_emergency_stop    # True if hardware emergency stop is pressed, rear cover is open or bumper is pressed. Does NOT include quick-stop relay.
bool quick_stop                 # True if the quick-stop relay has been triggered by collision avoidance or software emergency stop.

float64 wheel_encoder_left_ticks
float64 wheel_encoder_right_ticks

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','software_emergency_stop','hardware_emergency_stop','quick_stop','wheel_encoder_left_ticks','wheel_encoder_right_ticks']
  _slot_types = ['std_msgs/Header','bool','bool','bool','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,software_emergency_stop,hardware_emergency_stop,quick_stop,wheel_encoder_left_ticks,wheel_encoder_right_ticks

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SystemStatus, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.software_emergency_stop is None:
        self.software_emergency_stop = False
      if self.hardware_emergency_stop is None:
        self.hardware_emergency_stop = False
      if self.quick_stop is None:
        self.quick_stop = False
      if self.wheel_encoder_left_ticks is None:
        self.wheel_encoder_left_ticks = 0.
      if self.wheel_encoder_right_ticks is None:
        self.wheel_encoder_right_ticks = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.software_emergency_stop = False
      self.hardware_emergency_stop = False
      self.quick_stop = False
      self.wheel_encoder_left_ticks = 0.
      self.wheel_encoder_right_ticks = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3B2d.pack(_x.software_emergency_stop, _x.hardware_emergency_stop, _x.quick_stop, _x.wheel_encoder_left_ticks, _x.wheel_encoder_right_ticks))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 19
      (_x.software_emergency_stop, _x.hardware_emergency_stop, _x.quick_stop, _x.wheel_encoder_left_ticks, _x.wheel_encoder_right_ticks,) = _struct_3B2d.unpack(str[start:end])
      self.software_emergency_stop = bool(self.software_emergency_stop)
      self.hardware_emergency_stop = bool(self.hardware_emergency_stop)
      self.quick_stop = bool(self.quick_stop)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3B2d.pack(_x.software_emergency_stop, _x.hardware_emergency_stop, _x.quick_stop, _x.wheel_encoder_left_ticks, _x.wheel_encoder_right_ticks))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 19
      (_x.software_emergency_stop, _x.hardware_emergency_stop, _x.quick_stop, _x.wheel_encoder_left_ticks, _x.wheel_encoder_right_ticks,) = _struct_3B2d.unpack(str[start:end])
      self.software_emergency_stop = bool(self.software_emergency_stop)
      self.hardware_emergency_stop = bool(self.hardware_emergency_stop)
      self.quick_stop = bool(self.quick_stop)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3B2d = struct.Struct("<3B2d")
_struct_3I = struct.Struct("<3I")
