// Generated by gencpp from file situation_assessment_msgs/AddArea.msg
// DO NOT EDIT!


#ifndef SITUATION_ASSESSMENT_MSGS_MESSAGE_ADDAREA_H
#define SITUATION_ASSESSMENT_MSGS_MESSAGE_ADDAREA_H

#include <ros/service_traits.h>


#include <situation_assessment_msgs/AddAreaRequest.h>
#include <situation_assessment_msgs/AddAreaResponse.h>


namespace situation_assessment_msgs
{

struct AddArea
{

typedef AddAreaRequest Request;
typedef AddAreaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddArea
} // namespace situation_assessment_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::situation_assessment_msgs::AddArea > {
  static const char* value()
  {
    return "c38aa979dfb244cb438e150882c88332";
  }

  static const char* value(const ::situation_assessment_msgs::AddArea&) { return value(); }
};

template<>
struct DataType< ::situation_assessment_msgs::AddArea > {
  static const char* value()
  {
    return "situation_assessment_msgs/AddArea";
  }

  static const char* value(const ::situation_assessment_msgs::AddArea&) { return value(); }
};


// service_traits::MD5Sum< ::situation_assessment_msgs::AddAreaRequest> should match 
// service_traits::MD5Sum< ::situation_assessment_msgs::AddArea > 
template<>
struct MD5Sum< ::situation_assessment_msgs::AddAreaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::situation_assessment_msgs::AddArea >::value();
  }
  static const char* value(const ::situation_assessment_msgs::AddAreaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::situation_assessment_msgs::AddAreaRequest> should match 
// service_traits::DataType< ::situation_assessment_msgs::AddArea > 
template<>
struct DataType< ::situation_assessment_msgs::AddAreaRequest>
{
  static const char* value()
  {
    return DataType< ::situation_assessment_msgs::AddArea >::value();
  }
  static const char* value(const ::situation_assessment_msgs::AddAreaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::situation_assessment_msgs::AddAreaResponse> should match 
// service_traits::MD5Sum< ::situation_assessment_msgs::AddArea > 
template<>
struct MD5Sum< ::situation_assessment_msgs::AddAreaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::situation_assessment_msgs::AddArea >::value();
  }
  static const char* value(const ::situation_assessment_msgs::AddAreaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::situation_assessment_msgs::AddAreaResponse> should match 
// service_traits::DataType< ::situation_assessment_msgs::AddArea > 
template<>
struct DataType< ::situation_assessment_msgs::AddAreaResponse>
{
  static const char* value()
  {
    return DataType< ::situation_assessment_msgs::AddArea >::value();
  }
  static const char* value(const ::situation_assessment_msgs::AddAreaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SITUATION_ASSESSMENT_MSGS_MESSAGE_ADDAREA_H
