// Generated by gencpp from file situation_assessment_msgs/DatabaseRequestRequest.msg
// DO NOT EDIT!


#ifndef SITUATION_ASSESSMENT_MSGS_MESSAGE_DATABASEREQUESTREQUEST_H
#define SITUATION_ASSESSMENT_MSGS_MESSAGE_DATABASEREQUESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <situation_assessment_msgs/Fact.h>

namespace situation_assessment_msgs
{
template <class ContainerAllocator>
struct DatabaseRequestRequest_
{
  typedef DatabaseRequestRequest_<ContainerAllocator> Type;

  DatabaseRequestRequest_()
    : fact_list()  {
    }
  DatabaseRequestRequest_(const ContainerAllocator& _alloc)
    : fact_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::situation_assessment_msgs::Fact_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::situation_assessment_msgs::Fact_<ContainerAllocator> >::other >  _fact_list_type;
  _fact_list_type fact_list;




  typedef boost::shared_ptr< ::situation_assessment_msgs::DatabaseRequestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::situation_assessment_msgs::DatabaseRequestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DatabaseRequestRequest_

typedef ::situation_assessment_msgs::DatabaseRequestRequest_<std::allocator<void> > DatabaseRequestRequest;

typedef boost::shared_ptr< ::situation_assessment_msgs::DatabaseRequestRequest > DatabaseRequestRequestPtr;
typedef boost::shared_ptr< ::situation_assessment_msgs::DatabaseRequestRequest const> DatabaseRequestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::situation_assessment_msgs::DatabaseRequestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::situation_assessment_msgs::DatabaseRequestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace situation_assessment_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'situation_assessment_msgs': ['/home/zejian/catkin_ws/src/pedsim_ros/visualization/spencer_messages/supervision/situation_assessment_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::situation_assessment_msgs::DatabaseRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::situation_assessment_msgs::DatabaseRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::situation_assessment_msgs::DatabaseRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::situation_assessment_msgs::DatabaseRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::situation_assessment_msgs::DatabaseRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::situation_assessment_msgs::DatabaseRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::situation_assessment_msgs::DatabaseRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f1e6f5a8a358f42b96541cf3161904d";
  }

  static const char* value(const ::situation_assessment_msgs::DatabaseRequestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f1e6f5a8a358f42ULL;
  static const uint64_t static_value2 = 0xb96541cf3161904dULL;
};

template<class ContainerAllocator>
struct DataType< ::situation_assessment_msgs::DatabaseRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "situation_assessment_msgs/DatabaseRequestRequest";
  }

  static const char* value(const ::situation_assessment_msgs::DatabaseRequestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::situation_assessment_msgs::DatabaseRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Fact[] fact_list\n\
\n\
================================================================================\n\
MSG: situation_assessment_msgs/Fact\n\
string model\n\
string subject\n\
string[] predicate\n\
string[] value\n\
";
  }

  static const char* value(const ::situation_assessment_msgs::DatabaseRequestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::situation_assessment_msgs::DatabaseRequestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fact_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DatabaseRequestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::situation_assessment_msgs::DatabaseRequestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::situation_assessment_msgs::DatabaseRequestRequest_<ContainerAllocator>& v)
  {
    s << indent << "fact_list[]" << std::endl;
    for (size_t i = 0; i < v.fact_list.size(); ++i)
    {
      s << indent << "  fact_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::situation_assessment_msgs::Fact_<ContainerAllocator> >::stream(s, indent + "    ", v.fact_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SITUATION_ASSESSMENT_MSGS_MESSAGE_DATABASEREQUESTREQUEST_H
