// Generated by gencpp from file situation_assessment_msgs/GetMap.msg
// DO NOT EDIT!


#ifndef SITUATION_ASSESSMENT_MSGS_MESSAGE_GETMAP_H
#define SITUATION_ASSESSMENT_MSGS_MESSAGE_GETMAP_H

#include <ros/service_traits.h>


#include <situation_assessment_msgs/GetMapRequest.h>
#include <situation_assessment_msgs/GetMapResponse.h>


namespace situation_assessment_msgs
{

struct GetMap
{

typedef GetMapRequest Request;
typedef GetMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMap
} // namespace situation_assessment_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::situation_assessment_msgs::GetMap > {
  static const char* value()
  {
    return "aba73a71fb147c0d5f22018d68df9d81";
  }

  static const char* value(const ::situation_assessment_msgs::GetMap&) { return value(); }
};

template<>
struct DataType< ::situation_assessment_msgs::GetMap > {
  static const char* value()
  {
    return "situation_assessment_msgs/GetMap";
  }

  static const char* value(const ::situation_assessment_msgs::GetMap&) { return value(); }
};


// service_traits::MD5Sum< ::situation_assessment_msgs::GetMapRequest> should match 
// service_traits::MD5Sum< ::situation_assessment_msgs::GetMap > 
template<>
struct MD5Sum< ::situation_assessment_msgs::GetMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::situation_assessment_msgs::GetMap >::value();
  }
  static const char* value(const ::situation_assessment_msgs::GetMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::situation_assessment_msgs::GetMapRequest> should match 
// service_traits::DataType< ::situation_assessment_msgs::GetMap > 
template<>
struct DataType< ::situation_assessment_msgs::GetMapRequest>
{
  static const char* value()
  {
    return DataType< ::situation_assessment_msgs::GetMap >::value();
  }
  static const char* value(const ::situation_assessment_msgs::GetMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::situation_assessment_msgs::GetMapResponse> should match 
// service_traits::MD5Sum< ::situation_assessment_msgs::GetMap > 
template<>
struct MD5Sum< ::situation_assessment_msgs::GetMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::situation_assessment_msgs::GetMap >::value();
  }
  static const char* value(const ::situation_assessment_msgs::GetMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::situation_assessment_msgs::GetMapResponse> should match 
// service_traits::DataType< ::situation_assessment_msgs::GetMap > 
template<>
struct DataType< ::situation_assessment_msgs::GetMapResponse>
{
  static const char* value()
  {
    return DataType< ::situation_assessment_msgs::GetMap >::value();
  }
  static const char* value(const ::situation_assessment_msgs::GetMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SITUATION_ASSESSMENT_MSGS_MESSAGE_GETMAP_H
