// Generated by gencpp from file situation_assessment_msgs/HumanIntentionList.msg
// DO NOT EDIT!


#ifndef SITUATION_ASSESSMENT_MSGS_MESSAGE_HUMANINTENTIONLIST_H
#define SITUATION_ASSESSMENT_MSGS_MESSAGE_HUMANINTENTIONLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <situation_assessment_msgs/HumanIntention.h>

namespace situation_assessment_msgs
{
template <class ContainerAllocator>
struct HumanIntentionList_
{
  typedef HumanIntentionList_<ContainerAllocator> Type;

  HumanIntentionList_()
    : intention_list()  {
    }
  HumanIntentionList_(const ContainerAllocator& _alloc)
    : intention_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::situation_assessment_msgs::HumanIntention_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::situation_assessment_msgs::HumanIntention_<ContainerAllocator> >::other >  _intention_list_type;
  _intention_list_type intention_list;




  typedef boost::shared_ptr< ::situation_assessment_msgs::HumanIntentionList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::situation_assessment_msgs::HumanIntentionList_<ContainerAllocator> const> ConstPtr;

}; // struct HumanIntentionList_

typedef ::situation_assessment_msgs::HumanIntentionList_<std::allocator<void> > HumanIntentionList;

typedef boost::shared_ptr< ::situation_assessment_msgs::HumanIntentionList > HumanIntentionListPtr;
typedef boost::shared_ptr< ::situation_assessment_msgs::HumanIntentionList const> HumanIntentionListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::situation_assessment_msgs::HumanIntentionList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::situation_assessment_msgs::HumanIntentionList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace situation_assessment_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'situation_assessment_msgs': ['/home/zejian/catkin_ws/src/pedsim_ros/visualization/spencer_messages/supervision/situation_assessment_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::situation_assessment_msgs::HumanIntentionList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::situation_assessment_msgs::HumanIntentionList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::situation_assessment_msgs::HumanIntentionList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::situation_assessment_msgs::HumanIntentionList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::situation_assessment_msgs::HumanIntentionList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::situation_assessment_msgs::HumanIntentionList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::situation_assessment_msgs::HumanIntentionList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a92b36ed1214db8fa19a128a000085a";
  }

  static const char* value(const ::situation_assessment_msgs::HumanIntentionList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a92b36ed1214db8ULL;
  static const uint64_t static_value2 = 0xfa19a128a000085aULL;
};

template<class ContainerAllocator>
struct DataType< ::situation_assessment_msgs::HumanIntentionList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "situation_assessment_msgs/HumanIntentionList";
  }

  static const char* value(const ::situation_assessment_msgs::HumanIntentionList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::situation_assessment_msgs::HumanIntentionList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "HumanIntention[] intention_list\n\
================================================================================\n\
MSG: situation_assessment_msgs/HumanIntention\n\
string name\n\
string intention\n\
";
  }

  static const char* value(const ::situation_assessment_msgs::HumanIntentionList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::situation_assessment_msgs::HumanIntentionList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.intention_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HumanIntentionList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::situation_assessment_msgs::HumanIntentionList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::situation_assessment_msgs::HumanIntentionList_<ContainerAllocator>& v)
  {
    s << indent << "intention_list[]" << std::endl;
    for (size_t i = 0; i < v.intention_list.size(); ++i)
    {
      s << indent << "  intention_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::situation_assessment_msgs::HumanIntention_<ContainerAllocator> >::stream(s, indent + "    ", v.intention_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SITUATION_ASSESSMENT_MSGS_MESSAGE_HUMANINTENTIONLIST_H
