// Generated by gencpp from file situation_assessment_msgs/NamedPoseList.msg
// DO NOT EDIT!


#ifndef SITUATION_ASSESSMENT_MSGS_MESSAGE_NAMEDPOSELIST_H
#define SITUATION_ASSESSMENT_MSGS_MESSAGE_NAMEDPOSELIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <situation_assessment_msgs/NamedPose.h>

namespace situation_assessment_msgs
{
template <class ContainerAllocator>
struct NamedPoseList_
{
  typedef NamedPoseList_<ContainerAllocator> Type;

  NamedPoseList_()
    : poses()  {
    }
  NamedPoseList_(const ContainerAllocator& _alloc)
    : poses(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::situation_assessment_msgs::NamedPose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::situation_assessment_msgs::NamedPose_<ContainerAllocator> >::other >  _poses_type;
  _poses_type poses;




  typedef boost::shared_ptr< ::situation_assessment_msgs::NamedPoseList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::situation_assessment_msgs::NamedPoseList_<ContainerAllocator> const> ConstPtr;

}; // struct NamedPoseList_

typedef ::situation_assessment_msgs::NamedPoseList_<std::allocator<void> > NamedPoseList;

typedef boost::shared_ptr< ::situation_assessment_msgs::NamedPoseList > NamedPoseListPtr;
typedef boost::shared_ptr< ::situation_assessment_msgs::NamedPoseList const> NamedPoseListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::situation_assessment_msgs::NamedPoseList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::situation_assessment_msgs::NamedPoseList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace situation_assessment_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'situation_assessment_msgs': ['/home/zejian/catkin_ws/src/pedsim_ros/visualization/spencer_messages/supervision/situation_assessment_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::situation_assessment_msgs::NamedPoseList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::situation_assessment_msgs::NamedPoseList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::situation_assessment_msgs::NamedPoseList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::situation_assessment_msgs::NamedPoseList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::situation_assessment_msgs::NamedPoseList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::situation_assessment_msgs::NamedPoseList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::situation_assessment_msgs::NamedPoseList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f51355db5fbb7340b8ac6d2a18baad17";
  }

  static const char* value(const ::situation_assessment_msgs::NamedPoseList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf51355db5fbb7340ULL;
  static const uint64_t static_value2 = 0xb8ac6d2a18baad17ULL;
};

template<class ContainerAllocator>
struct DataType< ::situation_assessment_msgs::NamedPoseList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "situation_assessment_msgs/NamedPoseList";
  }

  static const char* value(const ::situation_assessment_msgs::NamedPoseList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::situation_assessment_msgs::NamedPoseList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "NamedPose[] poses\n\
================================================================================\n\
MSG: situation_assessment_msgs/NamedPose\n\
string name\n\
string type\n\
geometry_msgs/Pose pose\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::situation_assessment_msgs::NamedPoseList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::situation_assessment_msgs::NamedPoseList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NamedPoseList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::situation_assessment_msgs::NamedPoseList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::situation_assessment_msgs::NamedPoseList_<ContainerAllocator>& v)
  {
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::situation_assessment_msgs::NamedPose_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SITUATION_ASSESSMENT_MSGS_MESSAGE_NAMEDPOSELIST_H
