// Generated by gencpp from file situation_assessment_msgs/NameRequest.msg
// DO NOT EDIT!


#ifndef SITUATION_ASSESSMENT_MSGS_MESSAGE_NAMEREQUEST_H
#define SITUATION_ASSESSMENT_MSGS_MESSAGE_NAMEREQUEST_H

#include <ros/service_traits.h>


#include <situation_assessment_msgs/NameRequestRequest.h>
#include <situation_assessment_msgs/NameRequestResponse.h>


namespace situation_assessment_msgs
{

struct NameRequest
{

typedef NameRequestRequest Request;
typedef NameRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NameRequest
} // namespace situation_assessment_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::situation_assessment_msgs::NameRequest > {
  static const char* value()
  {
    return "ee91d68745ef4d7a247816a59dffedf2";
  }

  static const char* value(const ::situation_assessment_msgs::NameRequest&) { return value(); }
};

template<>
struct DataType< ::situation_assessment_msgs::NameRequest > {
  static const char* value()
  {
    return "situation_assessment_msgs/NameRequest";
  }

  static const char* value(const ::situation_assessment_msgs::NameRequest&) { return value(); }
};


// service_traits::MD5Sum< ::situation_assessment_msgs::NameRequestRequest> should match 
// service_traits::MD5Sum< ::situation_assessment_msgs::NameRequest > 
template<>
struct MD5Sum< ::situation_assessment_msgs::NameRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::situation_assessment_msgs::NameRequest >::value();
  }
  static const char* value(const ::situation_assessment_msgs::NameRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::situation_assessment_msgs::NameRequestRequest> should match 
// service_traits::DataType< ::situation_assessment_msgs::NameRequest > 
template<>
struct DataType< ::situation_assessment_msgs::NameRequestRequest>
{
  static const char* value()
  {
    return DataType< ::situation_assessment_msgs::NameRequest >::value();
  }
  static const char* value(const ::situation_assessment_msgs::NameRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::situation_assessment_msgs::NameRequestResponse> should match 
// service_traits::MD5Sum< ::situation_assessment_msgs::NameRequest > 
template<>
struct MD5Sum< ::situation_assessment_msgs::NameRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::situation_assessment_msgs::NameRequest >::value();
  }
  static const char* value(const ::situation_assessment_msgs::NameRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::situation_assessment_msgs::NameRequestResponse> should match 
// service_traits::DataType< ::situation_assessment_msgs::NameRequest > 
template<>
struct DataType< ::situation_assessment_msgs::NameRequestResponse>
{
  static const char* value()
  {
    return DataType< ::situation_assessment_msgs::NameRequest >::value();
  }
  static const char* value(const ::situation_assessment_msgs::NameRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SITUATION_ASSESSMENT_MSGS_MESSAGE_NAMEREQUEST_H
