// Generated by gencpp from file spencer_control_msgs/GetMaxVelocity.msg
// DO NOT EDIT!


#ifndef SPENCER_CONTROL_MSGS_MESSAGE_GETMAXVELOCITY_H
#define SPENCER_CONTROL_MSGS_MESSAGE_GETMAXVELOCITY_H

#include <ros/service_traits.h>


#include <spencer_control_msgs/GetMaxVelocityRequest.h>
#include <spencer_control_msgs/GetMaxVelocityResponse.h>


namespace spencer_control_msgs
{

struct GetMaxVelocity
{

typedef GetMaxVelocityRequest Request;
typedef GetMaxVelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMaxVelocity
} // namespace spencer_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::spencer_control_msgs::GetMaxVelocity > {
  static const char* value()
  {
    return "c3d002ed0ab158592aaa625149bc3810";
  }

  static const char* value(const ::spencer_control_msgs::GetMaxVelocity&) { return value(); }
};

template<>
struct DataType< ::spencer_control_msgs::GetMaxVelocity > {
  static const char* value()
  {
    return "spencer_control_msgs/GetMaxVelocity";
  }

  static const char* value(const ::spencer_control_msgs::GetMaxVelocity&) { return value(); }
};


// service_traits::MD5Sum< ::spencer_control_msgs::GetMaxVelocityRequest> should match 
// service_traits::MD5Sum< ::spencer_control_msgs::GetMaxVelocity > 
template<>
struct MD5Sum< ::spencer_control_msgs::GetMaxVelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::spencer_control_msgs::GetMaxVelocity >::value();
  }
  static const char* value(const ::spencer_control_msgs::GetMaxVelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::spencer_control_msgs::GetMaxVelocityRequest> should match 
// service_traits::DataType< ::spencer_control_msgs::GetMaxVelocity > 
template<>
struct DataType< ::spencer_control_msgs::GetMaxVelocityRequest>
{
  static const char* value()
  {
    return DataType< ::spencer_control_msgs::GetMaxVelocity >::value();
  }
  static const char* value(const ::spencer_control_msgs::GetMaxVelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::spencer_control_msgs::GetMaxVelocityResponse> should match 
// service_traits::MD5Sum< ::spencer_control_msgs::GetMaxVelocity > 
template<>
struct MD5Sum< ::spencer_control_msgs::GetMaxVelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::spencer_control_msgs::GetMaxVelocity >::value();
  }
  static const char* value(const ::spencer_control_msgs::GetMaxVelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::spencer_control_msgs::GetMaxVelocityResponse> should match 
// service_traits::DataType< ::spencer_control_msgs::GetMaxVelocity > 
template<>
struct DataType< ::spencer_control_msgs::GetMaxVelocityResponse>
{
  static const char* value()
  {
    return DataType< ::spencer_control_msgs::GetMaxVelocity >::value();
  }
  static const char* value(const ::spencer_control_msgs::GetMaxVelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPENCER_CONTROL_MSGS_MESSAGE_GETMAXVELOCITY_H
