// Generated by gencpp from file spencer_control_msgs/LocalizationStatus.msg
// DO NOT EDIT!


#ifndef SPENCER_CONTROL_MSGS_MESSAGE_LOCALIZATIONSTATUS_H
#define SPENCER_CONTROL_MSGS_MESSAGE_LOCALIZATIONSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace spencer_control_msgs
{
template <class ContainerAllocator>
struct LocalizationStatus_
{
  typedef LocalizationStatus_<ContainerAllocator> Type;

  LocalizationStatus_()
    : header()
    , confidence(0.0)
    , covariance()  {
      covariance.assign(0.0);
  }
  LocalizationStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , confidence(0.0)
    , covariance()  {
  (void)_alloc;
      covariance.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _confidence_type;
  _confidence_type confidence;

   typedef boost::array<double, 9>  _covariance_type;
  _covariance_type covariance;




  typedef boost::shared_ptr< ::spencer_control_msgs::LocalizationStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spencer_control_msgs::LocalizationStatus_<ContainerAllocator> const> ConstPtr;

}; // struct LocalizationStatus_

typedef ::spencer_control_msgs::LocalizationStatus_<std::allocator<void> > LocalizationStatus;

typedef boost::shared_ptr< ::spencer_control_msgs::LocalizationStatus > LocalizationStatusPtr;
typedef boost::shared_ptr< ::spencer_control_msgs::LocalizationStatus const> LocalizationStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spencer_control_msgs::LocalizationStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spencer_control_msgs::LocalizationStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace spencer_control_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'spencer_control_msgs': ['/home/zejian/catkin_ws/src/pedsim_ros/visualization/spencer_messages/control/spencer_control_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::spencer_control_msgs::LocalizationStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spencer_control_msgs::LocalizationStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spencer_control_msgs::LocalizationStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spencer_control_msgs::LocalizationStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spencer_control_msgs::LocalizationStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spencer_control_msgs::LocalizationStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spencer_control_msgs::LocalizationStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d88f744d11cfc084f86be4e548695ade";
  }

  static const char* value(const ::spencer_control_msgs::LocalizationStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd88f744d11cfc084ULL;
  static const uint64_t static_value2 = 0xf86be4e548695adeULL;
};

template<class ContainerAllocator>
struct DataType< ::spencer_control_msgs::LocalizationStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spencer_control_msgs/LocalizationStatus";
  }

  static const char* value(const ::spencer_control_msgs::LocalizationStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spencer_control_msgs::LocalizationStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
float64 confidence        # localization confidence\n\
float64[9] covariance     # of the particle cloud, not the pose!\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::spencer_control_msgs::LocalizationStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spencer_control_msgs::LocalizationStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.confidence);
      stream.next(m.covariance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalizationStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spencer_control_msgs::LocalizationStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spencer_control_msgs::LocalizationStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "confidence: ";
    Printer<double>::stream(s, indent + "  ", v.confidence);
    s << indent << "covariance[]" << std::endl;
    for (size_t i = 0; i < v.covariance.size(); ++i)
    {
      s << indent << "  covariance[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.covariance[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPENCER_CONTROL_MSGS_MESSAGE_LOCALIZATIONSTATUS_H
