// Generated by gencpp from file spencer_control_msgs/ReleaseEmergencyStop.msg
// DO NOT EDIT!


#ifndef SPENCER_CONTROL_MSGS_MESSAGE_RELEASEEMERGENCYSTOP_H
#define SPENCER_CONTROL_MSGS_MESSAGE_RELEASEEMERGENCYSTOP_H

#include <ros/service_traits.h>


#include <spencer_control_msgs/ReleaseEmergencyStopRequest.h>
#include <spencer_control_msgs/ReleaseEmergencyStopResponse.h>


namespace spencer_control_msgs
{

struct ReleaseEmergencyStop
{

typedef ReleaseEmergencyStopRequest Request;
typedef ReleaseEmergencyStopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReleaseEmergencyStop
} // namespace spencer_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::spencer_control_msgs::ReleaseEmergencyStop > {
  static const char* value()
  {
    return "1669ac49779199ede2945a8648a7b2a0";
  }

  static const char* value(const ::spencer_control_msgs::ReleaseEmergencyStop&) { return value(); }
};

template<>
struct DataType< ::spencer_control_msgs::ReleaseEmergencyStop > {
  static const char* value()
  {
    return "spencer_control_msgs/ReleaseEmergencyStop";
  }

  static const char* value(const ::spencer_control_msgs::ReleaseEmergencyStop&) { return value(); }
};


// service_traits::MD5Sum< ::spencer_control_msgs::ReleaseEmergencyStopRequest> should match 
// service_traits::MD5Sum< ::spencer_control_msgs::ReleaseEmergencyStop > 
template<>
struct MD5Sum< ::spencer_control_msgs::ReleaseEmergencyStopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::spencer_control_msgs::ReleaseEmergencyStop >::value();
  }
  static const char* value(const ::spencer_control_msgs::ReleaseEmergencyStopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::spencer_control_msgs::ReleaseEmergencyStopRequest> should match 
// service_traits::DataType< ::spencer_control_msgs::ReleaseEmergencyStop > 
template<>
struct DataType< ::spencer_control_msgs::ReleaseEmergencyStopRequest>
{
  static const char* value()
  {
    return DataType< ::spencer_control_msgs::ReleaseEmergencyStop >::value();
  }
  static const char* value(const ::spencer_control_msgs::ReleaseEmergencyStopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::spencer_control_msgs::ReleaseEmergencyStopResponse> should match 
// service_traits::MD5Sum< ::spencer_control_msgs::ReleaseEmergencyStop > 
template<>
struct MD5Sum< ::spencer_control_msgs::ReleaseEmergencyStopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::spencer_control_msgs::ReleaseEmergencyStop >::value();
  }
  static const char* value(const ::spencer_control_msgs::ReleaseEmergencyStopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::spencer_control_msgs::ReleaseEmergencyStopResponse> should match 
// service_traits::DataType< ::spencer_control_msgs::ReleaseEmergencyStop > 
template<>
struct DataType< ::spencer_control_msgs::ReleaseEmergencyStopResponse>
{
  static const char* value()
  {
    return DataType< ::spencer_control_msgs::ReleaseEmergencyStop >::value();
  }
  static const char* value(const ::spencer_control_msgs::ReleaseEmergencyStopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPENCER_CONTROL_MSGS_MESSAGE_RELEASEEMERGENCYSTOP_H
