(cl:defpackage spencer_nav_msgs-msg
  (:use )
  (:export
   "<NAVIGATIONPLANREQUESTTOPOLOGICAL>"
   "NAVIGATIONPLANREQUESTTOPOLOGICAL"
   "<NAVIGATIONPLANREQUESTGEOMETRIC>"
   "NAVIGATIONPLANREQUESTGEOMETRIC"
   "<NAVPARAMS>"
   "NAVPARAMS"
  ))

