; Auto-generated. Do not edit!


(cl:in-package supervision_msgs-msg)


;//! \htmlinclude ApproachResult.msg.html

(cl:defclass <ApproachResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ApproachResult (<ApproachResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ApproachResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ApproachResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name supervision_msgs-msg:<ApproachResult> is deprecated: use supervision_msgs-msg:ApproachResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <ApproachResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader supervision_msgs-msg:result-val is deprecated.  Use supervision_msgs-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ApproachResult>) ostream)
  "Serializes a message object of type '<ApproachResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'result) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ApproachResult>) istream)
  "Deserializes a message object of type '<ApproachResult>"
    (cl:setf (cl:slot-value msg 'result) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ApproachResult>)))
  "Returns string type for a message object of type '<ApproachResult>"
  "supervision_msgs/ApproachResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ApproachResult)))
  "Returns string type for a message object of type 'ApproachResult"
  "supervision_msgs/ApproachResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ApproachResult>)))
  "Returns md5sum for a message object of type '<ApproachResult>"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ApproachResult)))
  "Returns md5sum for a message object of type 'ApproachResult"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ApproachResult>)))
  "Returns full string definition for message of type '<ApproachResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ApproachResult)))
  "Returns full string definition for message of type 'ApproachResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ApproachResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ApproachResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ApproachResult
    (cl:cons ':result (result msg))
))
