; Auto-generated. Do not edit!


(cl:in-package supervision_msgs-msg)


;//! \htmlinclude ApproachGoal.msg.html

(cl:defclass <ApproachGoal> (roslisp-msg-protocol:ros-message)
  ((group_id
    :reader group_id
    :initarg :group_id
    :type cl:string
    :initform ""))
)

(cl:defclass ApproachGoal (<ApproachGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ApproachGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ApproachGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name supervision_msgs-msg:<ApproachGoal> is deprecated: use supervision_msgs-msg:ApproachGoal instead.")))

(cl:ensure-generic-function 'group_id-val :lambda-list '(m))
(cl:defmethod group_id-val ((m <ApproachGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader supervision_msgs-msg:group_id-val is deprecated.  Use supervision_msgs-msg:group_id instead.")
  (group_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ApproachGoal>) ostream)
  "Serializes a message object of type '<ApproachGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'group_id))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'group_id))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ApproachGoal>) istream)
  "Deserializes a message object of type '<ApproachGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'group_id) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'group_id) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ApproachGoal>)))
  "Returns string type for a message object of type '<ApproachGoal>"
  "supervision_msgs/ApproachGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ApproachGoal)))
  "Returns string type for a message object of type 'ApproachGoal"
  "supervision_msgs/ApproachGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ApproachGoal>)))
  "Returns md5sum for a message object of type '<ApproachGoal>"
  "bbd5aee54fe71bf370eff8c096080287")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ApproachGoal)))
  "Returns md5sum for a message object of type 'ApproachGoal"
  "bbd5aee54fe71bf370eff8c096080287")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ApproachGoal>)))
  "Returns full string definition for message of type '<ApproachGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string group_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ApproachGoal)))
  "Returns full string definition for message of type 'ApproachGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string group_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ApproachGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'group_id))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ApproachGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ApproachGoal
    (cl:cons ':group_id (group_id msg))
))
