; Auto-generated. Do not edit!


(cl:in-package supervision_msgs-msg)


;//! \htmlinclude MoveToPoseFeedback.msg.html

(cl:defclass <MoveToPoseFeedback> (roslisp-msg-protocol:ros-message)
  ((last_pose
    :reader last_pose
    :initarg :last_pose
    :type (cl:vector geometry_msgs-msg:Pose)
   :initform (cl:make-array 0 :element-type 'geometry_msgs-msg:Pose :initial-element (cl:make-instance 'geometry_msgs-msg:Pose))))
)

(cl:defclass MoveToPoseFeedback (<MoveToPoseFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveToPoseFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveToPoseFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name supervision_msgs-msg:<MoveToPoseFeedback> is deprecated: use supervision_msgs-msg:MoveToPoseFeedback instead.")))

(cl:ensure-generic-function 'last_pose-val :lambda-list '(m))
(cl:defmethod last_pose-val ((m <MoveToPoseFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader supervision_msgs-msg:last_pose-val is deprecated.  Use supervision_msgs-msg:last_pose instead.")
  (last_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveToPoseFeedback>) ostream)
  "Serializes a message object of type '<MoveToPoseFeedback>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'last_pose))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'last_pose))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveToPoseFeedback>) istream)
  "Deserializes a message object of type '<MoveToPoseFeedback>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'last_pose) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'last_pose)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'geometry_msgs-msg:Pose))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveToPoseFeedback>)))
  "Returns string type for a message object of type '<MoveToPoseFeedback>"
  "supervision_msgs/MoveToPoseFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveToPoseFeedback)))
  "Returns string type for a message object of type 'MoveToPoseFeedback"
  "supervision_msgs/MoveToPoseFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveToPoseFeedback>)))
  "Returns md5sum for a message object of type '<MoveToPoseFeedback>"
  "eedb0c3cc4c066c2f29f23f55a78bb1b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveToPoseFeedback)))
  "Returns md5sum for a message object of type 'MoveToPoseFeedback"
  "eedb0c3cc4c066c2f29f23f55a78bb1b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveToPoseFeedback>)))
  "Returns full string definition for message of type '<MoveToPoseFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/Pose[] last_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveToPoseFeedback)))
  "Returns full string definition for message of type 'MoveToPoseFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/Pose[] last_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveToPoseFeedback>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'last_pose) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveToPoseFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveToPoseFeedback
    (cl:cons ':last_pose (last_pose msg))
))
