(cl:defpackage pedsim_srvs-srv
  (:use )
  (:export
   "GETALLAGENTSSTATE"
   "<GETALLAGENTSSTATE-REQUEST>"
   "GETALLAGENTSSTATE-REQUEST"
   "<GETALLAGENTSSTATE-RESPONSE>"
   "GETALLAGENTSSTATE-RESPONSE"
   "GETAGENTSTATE"
   "<GETAGENTSTATE-REQUEST>"
   "GETAGENTSTATE-REQUEST"
   "<GETAGENTSTATE-RESPONSE>"
   "GETAGENTSTATE-RESPONSE"
   "SETALLAGENTSSTATE"
   "<SETALLAGENTSSTATE-REQUEST>"
   "SETALLAGENTSSTATE-REQUEST"
   "<SETALLAGENTSSTATE-RESPONSE>"
   "SETALLAGENTSSTATE-RESPONSE"
   "SETAGENTSTATE"
   "<SETAGENTSTATE-REQUEST>"
   "SETAGENTSTATE-REQUEST"
   "<SETAGENTSTATE-RESPONSE>"
   "SETAGENTSTATE-RESPONSE"
  ))

