(cl:defpackage spencer_control_msgs-msg
  (:use )
  (:export
   "<SYSTEMSTATUS>"
   "SYSTEMSTATUS"
   "<LOCALIZATIONSTATUS>"
   "LOCALIZATIONSTATUS"
   "<SAFETYRECTANGLE>"
   "SAFETYRECTANGLE"
   "<COLLISIONSTATUS>"
   "COLLISIONSTATUS"
   "<LOCALISATIONSTATUS>"
   "LOCALISATIONSTATUS"
   "<SETHEADJOINTPOSITION>"
   "SETHEADJOINTPOSITION"
   "<COMPONENTSTATUS>"
   "COMPONENTSTATUS"
   "<SETHEADJOINTVELOCITY>"
   "SETHEADJOINTVELOCITY"
  ))

