(cl:in-package spencer_control_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SOFTWARE_EMERGENCY_STOP-VAL
          SOFTWARE_EMERGENCY_STOP
          HARDWARE_EMERGENCY_STOP-VAL
          HARDWARE_EMERGENCY_STOP
          QUICK_STOP-VAL
          QUICK_STOP
          WHEEL_ENCODER_LEFT_TICKS-VAL
          WHEEL_ENCODER_LEFT_TICKS
          WHEEL_ENCODER_RIGHT_TICKS-VAL
          WHEEL_ENCODER_RIGHT_TICKS
))