(cl:defpackage spencer_control_msgs-srv
  (:use )
  (:export
   "RELEASEEMERGENCYSTOP"
   "<RELEASEEMERGENCYSTOP-REQUEST>"
   "RELEASEEMERGENCYSTOP-REQUEST"
   "<RELEASEEMERGENCYSTOP-RESPONSE>"
   "RELEASEEMERGENCYSTOP-RESPONSE"
   "GETMAXVELOCITY"
   "<GETMAXVELOCITY-REQUEST>"
   "GETMAXVELOCITY-REQUEST"
   "<GETMAXVELOCITY-RESPONSE>"
   "GETMAXVELOCITY-RESPONSE"
   "SETEMERGENCYSTOP"
   "<SETEMERGENCYSTOP-REQUEST>"
   "SETEMERGENCYSTOP-REQUEST"
   "<SETEMERGENCYSTOP-RESPONSE>"
   "SETEMERGENCYSTOP-RESPONSE"
   "SETMAXVELOCITY"
   "<SETMAXVELOCITY-REQUEST>"
   "SETMAXVELOCITY-REQUEST"
   "<SETMAXVELOCITY-RESPONSE>"
   "SETMAXVELOCITY-RESPONSE"
  ))

