# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from supervision_msgs/PathInfo.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PathInfo(genpy.Message):
  _md5sum = "14255af10539725f58e7cb7d2173aba9"
  _type = "supervision_msgs/PathInfo"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 total_seconds
float32 total_length
int16 remaining_seconds
float32 remaining_length"""
  __slots__ = ['total_seconds','total_length','remaining_seconds','remaining_length']
  _slot_types = ['int16','float32','int16','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       total_seconds,total_length,remaining_seconds,remaining_length

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PathInfo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.total_seconds is None:
        self.total_seconds = 0
      if self.total_length is None:
        self.total_length = 0.
      if self.remaining_seconds is None:
        self.remaining_seconds = 0
      if self.remaining_length is None:
        self.remaining_length = 0.
    else:
      self.total_seconds = 0
      self.total_length = 0.
      self.remaining_seconds = 0
      self.remaining_length = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_hfhf.pack(_x.total_seconds, _x.total_length, _x.remaining_seconds, _x.remaining_length))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.total_seconds, _x.total_length, _x.remaining_seconds, _x.remaining_length,) = _struct_hfhf.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_hfhf.pack(_x.total_seconds, _x.total_length, _x.remaining_seconds, _x.remaining_length))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.total_seconds, _x.total_length, _x.remaining_seconds, _x.remaining_length,) = _struct_hfhf.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_hfhf = struct.Struct("<hfhf")
