# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from supervision_msgs/SupervisionStopped.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SupervisionStopped(genpy.Message):
  _md5sum = "199f785df4f375bed5b36a8d78b2b2c1"
  _type = "supervision_msgs/SupervisionStopped"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool is_stopped
bool is_paused"""
  __slots__ = ['is_stopped','is_paused']
  _slot_types = ['bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       is_stopped,is_paused

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SupervisionStopped, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.is_stopped is None:
        self.is_stopped = False
      if self.is_paused is None:
        self.is_paused = False
    else:
      self.is_stopped = False
      self.is_paused = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2B.pack(_x.is_stopped, _x.is_paused))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.is_stopped, _x.is_paused,) = _struct_2B.unpack(str[start:end])
      self.is_stopped = bool(self.is_stopped)
      self.is_paused = bool(self.is_paused)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2B.pack(_x.is_stopped, _x.is_paused))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.is_stopped, _x.is_paused,) = _struct_2B.unpack(str[start:end])
      self.is_stopped = bool(self.is_stopped)
      self.is_paused = bool(self.is_paused)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2B = struct.Struct("<2B")
