(cl:defpackage spencer_mapping_msgs-srv
  (:use )
  (:export
   "SETINTERESTREGION"
   "<SETINTERESTREGION-REQUEST>"
   "SETINTERESTREGION-REQUEST"
   "<SETINTERESTREGION-RESPONSE>"
   "SETINTERESTREGION-RESPONSE"
   "LABEL"
   "<LABEL-REQUEST>"
   "LABEL-REQUEST"
   "<LABEL-RESPONSE>"
   "LABEL-RESPONSE"
   "LABELS"
   "<LABELS-REQUEST>"
   "LABELS-REQUEST"
   "<LABELS-RESPONSE>"
   "LABELS-RESPONSE"
  ))

