// Generated by gencpp from file spencer_nav_msgs/NavParams.msg
// DO NOT EDIT!


#ifndef SPENCER_NAV_MSGS_MESSAGE_NAVPARAMS_H
#define SPENCER_NAV_MSGS_MESSAGE_NAVPARAMS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace spencer_nav_msgs
{
template <class ContainerAllocator>
struct NavParams_
{
  typedef NavParams_<ContainerAllocator> Type;

  NavParams_()
    : header()
    , directional_cost(false)  {
    }
  NavParams_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , directional_cost(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _directional_cost_type;
  _directional_cost_type directional_cost;




  typedef boost::shared_ptr< ::spencer_nav_msgs::NavParams_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spencer_nav_msgs::NavParams_<ContainerAllocator> const> ConstPtr;

}; // struct NavParams_

typedef ::spencer_nav_msgs::NavParams_<std::allocator<void> > NavParams;

typedef boost::shared_ptr< ::spencer_nav_msgs::NavParams > NavParamsPtr;
typedef boost::shared_ptr< ::spencer_nav_msgs::NavParams const> NavParamsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spencer_nav_msgs::NavParams_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spencer_nav_msgs::NavParams_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace spencer_nav_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'spencer_tracking_msgs': ['/home/zejian/catkin_ws/src/pedsim_ros/visualization/spencer_messages/perception/spencer_tracking_msgs/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'spencer_nav_msgs': ['/home/zejian/catkin_ws/src/pedsim_ros/visualization/spencer_messages/planning/spencer_nav_msgs/msg'], 'spencer_mapping_msgs': ['/home/zejian/catkin_ws/src/pedsim_ros/visualization/spencer_messages/mapping/spencer_mapping_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::spencer_nav_msgs::NavParams_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spencer_nav_msgs::NavParams_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spencer_nav_msgs::NavParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spencer_nav_msgs::NavParams_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spencer_nav_msgs::NavParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spencer_nav_msgs::NavParams_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spencer_nav_msgs::NavParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "547b70165ad41488198076dece27b8c7";
  }

  static const char* value(const ::spencer_nav_msgs::NavParams_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x547b70165ad41488ULL;
  static const uint64_t static_value2 = 0x198076dece27b8c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::spencer_nav_msgs::NavParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spencer_nav_msgs/NavParams";
  }

  static const char* value(const ::spencer_nav_msgs::NavParams_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spencer_nav_msgs::NavParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# message defining a parameters or strategies for motion planner to adapt based on input from learning\n\
\n\
Header header\n\
bool directional_cost	# if to use directional_cost model or not\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::spencer_nav_msgs::NavParams_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spencer_nav_msgs::NavParams_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.directional_cost);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavParams_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spencer_nav_msgs::NavParams_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spencer_nav_msgs::NavParams_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "directional_cost: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.directional_cost);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPENCER_NAV_MSGS_MESSAGE_NAVPARAMS_H
