// Generated by gencpp from file spencer_nav_msgs/SetDrivingDirection.msg
// DO NOT EDIT!


#ifndef SPENCER_NAV_MSGS_MESSAGE_SETDRIVINGDIRECTION_H
#define SPENCER_NAV_MSGS_MESSAGE_SETDRIVINGDIRECTION_H

#include <ros/service_traits.h>


#include <spencer_nav_msgs/SetDrivingDirectionRequest.h>
#include <spencer_nav_msgs/SetDrivingDirectionResponse.h>


namespace spencer_nav_msgs
{

struct SetDrivingDirection
{

typedef SetDrivingDirectionRequest Request;
typedef SetDrivingDirectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDrivingDirection
} // namespace spencer_nav_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::spencer_nav_msgs::SetDrivingDirection > {
  static const char* value()
  {
    return "d9fd33ff14b7b1818fbbdfcd99a85b57";
  }

  static const char* value(const ::spencer_nav_msgs::SetDrivingDirection&) { return value(); }
};

template<>
struct DataType< ::spencer_nav_msgs::SetDrivingDirection > {
  static const char* value()
  {
    return "spencer_nav_msgs/SetDrivingDirection";
  }

  static const char* value(const ::spencer_nav_msgs::SetDrivingDirection&) { return value(); }
};


// service_traits::MD5Sum< ::spencer_nav_msgs::SetDrivingDirectionRequest> should match 
// service_traits::MD5Sum< ::spencer_nav_msgs::SetDrivingDirection > 
template<>
struct MD5Sum< ::spencer_nav_msgs::SetDrivingDirectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::spencer_nav_msgs::SetDrivingDirection >::value();
  }
  static const char* value(const ::spencer_nav_msgs::SetDrivingDirectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::spencer_nav_msgs::SetDrivingDirectionRequest> should match 
// service_traits::DataType< ::spencer_nav_msgs::SetDrivingDirection > 
template<>
struct DataType< ::spencer_nav_msgs::SetDrivingDirectionRequest>
{
  static const char* value()
  {
    return DataType< ::spencer_nav_msgs::SetDrivingDirection >::value();
  }
  static const char* value(const ::spencer_nav_msgs::SetDrivingDirectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::spencer_nav_msgs::SetDrivingDirectionResponse> should match 
// service_traits::MD5Sum< ::spencer_nav_msgs::SetDrivingDirection > 
template<>
struct MD5Sum< ::spencer_nav_msgs::SetDrivingDirectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::spencer_nav_msgs::SetDrivingDirection >::value();
  }
  static const char* value(const ::spencer_nav_msgs::SetDrivingDirectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::spencer_nav_msgs::SetDrivingDirectionResponse> should match 
// service_traits::DataType< ::spencer_nav_msgs::SetDrivingDirection > 
template<>
struct DataType< ::spencer_nav_msgs::SetDrivingDirectionResponse>
{
  static const char* value()
  {
    return DataType< ::spencer_nav_msgs::SetDrivingDirection >::value();
  }
  static const char* value(const ::spencer_nav_msgs::SetDrivingDirectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPENCER_NAV_MSGS_MESSAGE_SETDRIVINGDIRECTION_H
