// Generated by gencpp from file spencer_nav_msgs/SetDrivingDirectionRequest.msg
// DO NOT EDIT!


#ifndef SPENCER_NAV_MSGS_MESSAGE_SETDRIVINGDIRECTIONREQUEST_H
#define SPENCER_NAV_MSGS_MESSAGE_SETDRIVINGDIRECTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace spencer_nav_msgs
{
template <class ContainerAllocator>
struct SetDrivingDirectionRequest_
{
  typedef SetDrivingDirectionRequest_<ContainerAllocator> Type;

  SetDrivingDirectionRequest_()
    : backward(false)  {
    }
  SetDrivingDirectionRequest_(const ContainerAllocator& _alloc)
    : backward(false)  {
  (void)_alloc;
    }



   typedef uint8_t _backward_type;
  _backward_type backward;




  typedef boost::shared_ptr< ::spencer_nav_msgs::SetDrivingDirectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spencer_nav_msgs::SetDrivingDirectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetDrivingDirectionRequest_

typedef ::spencer_nav_msgs::SetDrivingDirectionRequest_<std::allocator<void> > SetDrivingDirectionRequest;

typedef boost::shared_ptr< ::spencer_nav_msgs::SetDrivingDirectionRequest > SetDrivingDirectionRequestPtr;
typedef boost::shared_ptr< ::spencer_nav_msgs::SetDrivingDirectionRequest const> SetDrivingDirectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spencer_nav_msgs::SetDrivingDirectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spencer_nav_msgs::SetDrivingDirectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace spencer_nav_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'spencer_tracking_msgs': ['/home/zejian/catkin_ws/src/pedsim_ros/visualization/spencer_messages/perception/spencer_tracking_msgs/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'spencer_nav_msgs': ['/home/zejian/catkin_ws/src/pedsim_ros/visualization/spencer_messages/planning/spencer_nav_msgs/msg'], 'spencer_mapping_msgs': ['/home/zejian/catkin_ws/src/pedsim_ros/visualization/spencer_messages/mapping/spencer_mapping_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::spencer_nav_msgs::SetDrivingDirectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spencer_nav_msgs::SetDrivingDirectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spencer_nav_msgs::SetDrivingDirectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spencer_nav_msgs::SetDrivingDirectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spencer_nav_msgs::SetDrivingDirectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spencer_nav_msgs::SetDrivingDirectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spencer_nav_msgs::SetDrivingDirectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9fd33ff14b7b1818fbbdfcd99a85b57";
  }

  static const char* value(const ::spencer_nav_msgs::SetDrivingDirectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9fd33ff14b7b181ULL;
  static const uint64_t static_value2 = 0x8fbbdfcd99a85b57ULL;
};

template<class ContainerAllocator>
struct DataType< ::spencer_nav_msgs::SetDrivingDirectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spencer_nav_msgs/SetDrivingDirectionRequest";
  }

  static const char* value(const ::spencer_nav_msgs::SetDrivingDirectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spencer_nav_msgs::SetDrivingDirectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool    backward\n\
";
  }

  static const char* value(const ::spencer_nav_msgs::SetDrivingDirectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spencer_nav_msgs::SetDrivingDirectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.backward);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetDrivingDirectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spencer_nav_msgs::SetDrivingDirectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spencer_nav_msgs::SetDrivingDirectionRequest_<ContainerAllocator>& v)
  {
    s << indent << "backward: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.backward);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPENCER_NAV_MSGS_MESSAGE_SETDRIVINGDIRECTIONREQUEST_H
