// Generated by gencpp from file spencer_task_planner_msgs/GuidanceStatus.msg
// DO NOT EDIT!


#ifndef SPENCER_TASK_PLANNER_MSGS_MESSAGE_GUIDANCESTATUS_H
#define SPENCER_TASK_PLANNER_MSGS_MESSAGE_GUIDANCESTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace spencer_task_planner_msgs
{
template <class ContainerAllocator>
struct GuidanceStatus_
{
  typedef GuidanceStatus_<ContainerAllocator> Type;

  GuidanceStatus_()
    : status()  {
    }
  GuidanceStatus_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;


    static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  APPROACHING_PERSON;
     static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  GUIDING_PERSON;
     static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  WAITING_FOR_PERSON;
     static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  RETURNING_HOME;
 

  typedef boost::shared_ptr< ::spencer_task_planner_msgs::GuidanceStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spencer_task_planner_msgs::GuidanceStatus_<ContainerAllocator> const> ConstPtr;

}; // struct GuidanceStatus_

typedef ::spencer_task_planner_msgs::GuidanceStatus_<std::allocator<void> > GuidanceStatus;

typedef boost::shared_ptr< ::spencer_task_planner_msgs::GuidanceStatus > GuidanceStatusPtr;
typedef boost::shared_ptr< ::spencer_task_planner_msgs::GuidanceStatus const> GuidanceStatusConstPtr;

// constants requiring out of line definition

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      GuidanceStatus_<ContainerAllocator>::APPROACHING_PERSON =
        
          "approaching_person"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      GuidanceStatus_<ContainerAllocator>::GUIDING_PERSON =
        
          "guiding_person"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      GuidanceStatus_<ContainerAllocator>::WAITING_FOR_PERSON =
        
          "waiting_for_person"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      GuidanceStatus_<ContainerAllocator>::RETURNING_HOME =
        
          "returning_home"
        
        ;
   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spencer_task_planner_msgs::GuidanceStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spencer_task_planner_msgs::GuidanceStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace spencer_task_planner_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'spencer_task_planner_msgs': ['/home/zejian/catkin_ws/src/pedsim_ros/visualization/spencer_messages/planning/spencer_task_planner_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::spencer_task_planner_msgs::GuidanceStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spencer_task_planner_msgs::GuidanceStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spencer_task_planner_msgs::GuidanceStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spencer_task_planner_msgs::GuidanceStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spencer_task_planner_msgs::GuidanceStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spencer_task_planner_msgs::GuidanceStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spencer_task_planner_msgs::GuidanceStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a840bebb777d577f6fdf550700c525f";
  }

  static const char* value(const ::spencer_task_planner_msgs::GuidanceStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a840bebb777d577ULL;
  static const uint64_t static_value2 = 0xf6fdf550700c525fULL;
};

template<class ContainerAllocator>
struct DataType< ::spencer_task_planner_msgs::GuidanceStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spencer_task_planner_msgs/GuidanceStatus";
  }

  static const char* value(const ::spencer_task_planner_msgs::GuidanceStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spencer_task_planner_msgs::GuidanceStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string status\n\
\n\
# Use one of these constants for status:\n\
string APPROACHING_PERSON = approaching_person\n\
string GUIDING_PERSON = guiding_person\n\
string WAITING_FOR_PERSON = waiting_for_person\n\
string RETURNING_HOME = returning_home\n\
";
  }

  static const char* value(const ::spencer_task_planner_msgs::GuidanceStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spencer_task_planner_msgs::GuidanceStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GuidanceStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spencer_task_planner_msgs::GuidanceStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spencer_task_planner_msgs::GuidanceStatus_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPENCER_TASK_PLANNER_MSGS_MESSAGE_GUIDANCESTATUS_H
