(cl:defpackage spencer_nav_msgs-srv
  (:use )
  (:export
   "SETDRIVINGDIRECTION"
   "<SETDRIVINGDIRECTION-REQUEST>"
   "SETDRIVINGDIRECTION-REQUEST"
   "<SETDRIVINGDIRECTION-RESPONSE>"
   "SETDRIVINGDIRECTION-RESPONSE"
   "STOPDRIVING"
   "<STOPDRIVING-REQUEST>"
   "STOPDRIVING-REQUEST"
   "<STOPDRIVING-RESPONSE>"
   "STOPDRIVING-RESPONSE"
  ))

