// Generated by gencpp from file spencer_mapping_msgs/TopologicalMap.msg
// DO NOT EDIT!


#ifndef SPENCER_MAPPING_MSGS_MESSAGE_TOPOLOGICALMAP_H
#define SPENCER_MAPPING_MSGS_MESSAGE_TOPOLOGICALMAP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <spencer_mapping_msgs/TopologicalMapNode.h>
#include <spencer_mapping_msgs/TopologicalMapEdge.h>

namespace spencer_mapping_msgs
{
template <class ContainerAllocator>
struct TopologicalMap_
{
  typedef TopologicalMap_<ContainerAllocator> Type;

  TopologicalMap_()
    : nodes()
    , edges()  {
    }
  TopologicalMap_(const ContainerAllocator& _alloc)
    : nodes(_alloc)
    , edges(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::spencer_mapping_msgs::TopologicalMapNode_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::spencer_mapping_msgs::TopologicalMapNode_<ContainerAllocator> >::other >  _nodes_type;
  _nodes_type nodes;

   typedef std::vector< ::spencer_mapping_msgs::TopologicalMapEdge_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::spencer_mapping_msgs::TopologicalMapEdge_<ContainerAllocator> >::other >  _edges_type;
  _edges_type edges;




  typedef boost::shared_ptr< ::spencer_mapping_msgs::TopologicalMap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spencer_mapping_msgs::TopologicalMap_<ContainerAllocator> const> ConstPtr;

}; // struct TopologicalMap_

typedef ::spencer_mapping_msgs::TopologicalMap_<std::allocator<void> > TopologicalMap;

typedef boost::shared_ptr< ::spencer_mapping_msgs::TopologicalMap > TopologicalMapPtr;
typedef boost::shared_ptr< ::spencer_mapping_msgs::TopologicalMap const> TopologicalMapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spencer_mapping_msgs::TopologicalMap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spencer_mapping_msgs::TopologicalMap_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace spencer_mapping_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'spencer_mapping_msgs': ['/home/zejian/catkin_ws/src/pedsim_ros/visualization/spencer_messages/mapping/spencer_mapping_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::spencer_mapping_msgs::TopologicalMap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spencer_mapping_msgs::TopologicalMap_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spencer_mapping_msgs::TopologicalMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spencer_mapping_msgs::TopologicalMap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spencer_mapping_msgs::TopologicalMap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spencer_mapping_msgs::TopologicalMap_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spencer_mapping_msgs::TopologicalMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36ff17f5e065879348b7145dbd6ef195";
  }

  static const char* value(const ::spencer_mapping_msgs::TopologicalMap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36ff17f5e0658793ULL;
  static const uint64_t static_value2 = 0x48b7145dbd6ef195ULL;
};

template<class ContainerAllocator>
struct DataType< ::spencer_mapping_msgs::TopologicalMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spencer_mapping_msgs/TopologicalMap";
  }

  static const char* value(const ::spencer_mapping_msgs::TopologicalMap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spencer_mapping_msgs::TopologicalMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This format is adapted from the Fuerte topological_navigation stack.\n\
\n\
# A 2d topological map consists of a set of local occupancy grids together with\n\
# the transformations between coordinate frames of overlapping grids.  This ROS\n\
# message represents the structure of the topological map, i.e., all the \n\
# information except the grids themselves.  You can get individual grids by\n\
# calling the GetLocalGrid service on the mapper.\n\
\n\
TopologicalMapNode[] nodes\n\
TopologicalMapEdge[] edges\n\
\n\
================================================================================\n\
MSG: spencer_mapping_msgs/TopologicalMapNode\n\
# This format is adapted from the Fuerte topological_navigation stack.\n\
\n\
# Info stored with a node in a 2d topological map\n\
\n\
# Id of this node in the topological map\n\
uint32 id\n\
\n\
# position in the global map\n\
geometry_msgs/Point position\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: spencer_mapping_msgs/TopologicalMapEdge\n\
# This format is adapted from the Fuerte topological_navigation stack.\n\
\n\
# Info stored with an edge in the topological map\n\
\n\
# Id of this edge in the topological map\n\
uint32 id\n\
\n\
# Id of the source node\n\
uint32 src\n\
\n\
# Id of the destination node\n\
uint32 dest\n\
\n\
# Costs of this edge\n\
float32[] cost\n\
";
  }

  static const char* value(const ::spencer_mapping_msgs::TopologicalMap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spencer_mapping_msgs::TopologicalMap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nodes);
      stream.next(m.edges);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TopologicalMap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spencer_mapping_msgs::TopologicalMap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spencer_mapping_msgs::TopologicalMap_<ContainerAllocator>& v)
  {
    s << indent << "nodes[]" << std::endl;
    for (size_t i = 0; i < v.nodes.size(); ++i)
    {
      s << indent << "  nodes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::spencer_mapping_msgs::TopologicalMapNode_<ContainerAllocator> >::stream(s, indent + "    ", v.nodes[i]);
    }
    s << indent << "edges[]" << std::endl;
    for (size_t i = 0; i < v.edges.size(); ++i)
    {
      s << indent << "  edges[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::spencer_mapping_msgs::TopologicalMapEdge_<ContainerAllocator> >::stream(s, indent + "    ", v.edges[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPENCER_MAPPING_MSGS_MESSAGE_TOPOLOGICALMAP_H
