// Generated by gencpp from file supervision_msgs/CalculatePath.msg
// DO NOT EDIT!


#ifndef SUPERVISION_MSGS_MESSAGE_CALCULATEPATH_H
#define SUPERVISION_MSGS_MESSAGE_CALCULATEPATH_H

#include <ros/service_traits.h>


#include <supervision_msgs/CalculatePathRequest.h>
#include <supervision_msgs/CalculatePathResponse.h>


namespace supervision_msgs
{

struct CalculatePath
{

typedef CalculatePathRequest Request;
typedef CalculatePathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalculatePath
} // namespace supervision_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::supervision_msgs::CalculatePath > {
  static const char* value()
  {
    return "0e0b8412cb0804d38525492d9255edb1";
  }

  static const char* value(const ::supervision_msgs::CalculatePath&) { return value(); }
};

template<>
struct DataType< ::supervision_msgs::CalculatePath > {
  static const char* value()
  {
    return "supervision_msgs/CalculatePath";
  }

  static const char* value(const ::supervision_msgs::CalculatePath&) { return value(); }
};


// service_traits::MD5Sum< ::supervision_msgs::CalculatePathRequest> should match 
// service_traits::MD5Sum< ::supervision_msgs::CalculatePath > 
template<>
struct MD5Sum< ::supervision_msgs::CalculatePathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::supervision_msgs::CalculatePath >::value();
  }
  static const char* value(const ::supervision_msgs::CalculatePathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::supervision_msgs::CalculatePathRequest> should match 
// service_traits::DataType< ::supervision_msgs::CalculatePath > 
template<>
struct DataType< ::supervision_msgs::CalculatePathRequest>
{
  static const char* value()
  {
    return DataType< ::supervision_msgs::CalculatePath >::value();
  }
  static const char* value(const ::supervision_msgs::CalculatePathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::supervision_msgs::CalculatePathResponse> should match 
// service_traits::MD5Sum< ::supervision_msgs::CalculatePath > 
template<>
struct MD5Sum< ::supervision_msgs::CalculatePathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::supervision_msgs::CalculatePath >::value();
  }
  static const char* value(const ::supervision_msgs::CalculatePathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::supervision_msgs::CalculatePathResponse> should match 
// service_traits::DataType< ::supervision_msgs::CalculatePath > 
template<>
struct DataType< ::supervision_msgs::CalculatePathResponse>
{
  static const char* value()
  {
    return DataType< ::supervision_msgs::CalculatePath >::value();
  }
  static const char* value(const ::supervision_msgs::CalculatePathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUPERVISION_MSGS_MESSAGE_CALCULATEPATH_H
