// Generated by gencpp from file supervision_msgs/GuideFollowers.msg
// DO NOT EDIT!


#ifndef SUPERVISION_MSGS_MESSAGE_GUIDEFOLLOWERS_H
#define SUPERVISION_MSGS_MESSAGE_GUIDEFOLLOWERS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace supervision_msgs
{
template <class ContainerAllocator>
struct GuideFollowers_
{
  typedef GuideFollowers_<ContainerAllocator> Type;

  GuideFollowers_()
    : number(0)
    , ids()  {
    }
  GuideFollowers_(const ContainerAllocator& _alloc)
    : number(0)
    , ids(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _number_type;
  _number_type number;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _ids_type;
  _ids_type ids;




  typedef boost::shared_ptr< ::supervision_msgs::GuideFollowers_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::supervision_msgs::GuideFollowers_<ContainerAllocator> const> ConstPtr;

}; // struct GuideFollowers_

typedef ::supervision_msgs::GuideFollowers_<std::allocator<void> > GuideFollowers;

typedef boost::shared_ptr< ::supervision_msgs::GuideFollowers > GuideFollowersPtr;
typedef boost::shared_ptr< ::supervision_msgs::GuideFollowers const> GuideFollowersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::supervision_msgs::GuideFollowers_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::supervision_msgs::GuideFollowers_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace supervision_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'supervision_msgs': ['/home/zejian/catkin_ws/src/pedsim_ros/visualization/spencer_messages/supervision/supervision_msgs/msg', '/home/zejian/catkin_ws/devel/share/supervision_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::supervision_msgs::GuideFollowers_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::supervision_msgs::GuideFollowers_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::supervision_msgs::GuideFollowers_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::supervision_msgs::GuideFollowers_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::supervision_msgs::GuideFollowers_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::supervision_msgs::GuideFollowers_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::supervision_msgs::GuideFollowers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f2cd011711ade36dbf5eb279ddaf5ba";
  }

  static const char* value(const ::supervision_msgs::GuideFollowers_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f2cd011711ade36ULL;
  static const uint64_t static_value2 = 0xdbf5eb279ddaf5baULL;
};

template<class ContainerAllocator>
struct DataType< ::supervision_msgs::GuideFollowers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "supervision_msgs/GuideFollowers";
  }

  static const char* value(const ::supervision_msgs::GuideFollowers_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::supervision_msgs::GuideFollowers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 number\n\
string[] ids\n\
";
  }

  static const char* value(const ::supervision_msgs::GuideFollowers_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::supervision_msgs::GuideFollowers_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
      stream.next(m.ids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GuideFollowers_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::supervision_msgs::GuideFollowers_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::supervision_msgs::GuideFollowers_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<int16_t>::stream(s, indent + "  ", v.number);
    s << indent << "ids[]" << std::endl;
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      s << indent << "  ids[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ids[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUPERVISION_MSGS_MESSAGE_GUIDEFOLLOWERS_H
