// Generated by gencpp from file supervision_msgs/GuideGroupFeedback.msg
// DO NOT EDIT!


#ifndef SUPERVISION_MSGS_MESSAGE_GUIDEGROUPFEEDBACK_H
#define SUPERVISION_MSGS_MESSAGE_GUIDEGROUPFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace supervision_msgs
{
template <class ContainerAllocator>
struct GuideGroupFeedback_
{
  typedef GuideGroupFeedback_<ContainerAllocator> Type;

  GuideGroupFeedback_()
    : current_node()
    , status()
    , details()  {
    }
  GuideGroupFeedback_(const ContainerAllocator& _alloc)
    : current_node(_alloc)
    , status(_alloc)
    , details(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _current_node_type;
  _current_node_type current_node;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _details_type;
  _details_type details;




  typedef boost::shared_ptr< ::supervision_msgs::GuideGroupFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::supervision_msgs::GuideGroupFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct GuideGroupFeedback_

typedef ::supervision_msgs::GuideGroupFeedback_<std::allocator<void> > GuideGroupFeedback;

typedef boost::shared_ptr< ::supervision_msgs::GuideGroupFeedback > GuideGroupFeedbackPtr;
typedef boost::shared_ptr< ::supervision_msgs::GuideGroupFeedback const> GuideGroupFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::supervision_msgs::GuideGroupFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::supervision_msgs::GuideGroupFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace supervision_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'supervision_msgs': ['/home/zejian/catkin_ws/src/pedsim_ros/visualization/spencer_messages/supervision/supervision_msgs/msg', '/home/zejian/catkin_ws/devel/share/supervision_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::supervision_msgs::GuideGroupFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::supervision_msgs::GuideGroupFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::supervision_msgs::GuideGroupFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::supervision_msgs::GuideGroupFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::supervision_msgs::GuideGroupFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::supervision_msgs::GuideGroupFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::supervision_msgs::GuideGroupFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff5dc2d5c7947e422d7dbf80c347f3da";
  }

  static const char* value(const ::supervision_msgs::GuideGroupFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff5dc2d5c7947e42ULL;
  static const uint64_t static_value2 = 0x2d7dbf80c347f3daULL;
};

template<class ContainerAllocator>
struct DataType< ::supervision_msgs::GuideGroupFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "supervision_msgs/GuideGroupFeedback";
  }

  static const char* value(const ::supervision_msgs::GuideGroupFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::supervision_msgs::GuideGroupFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
string current_node\n\
string status\n\
string details\n\
";
  }

  static const char* value(const ::supervision_msgs::GuideGroupFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::supervision_msgs::GuideGroupFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_node);
      stream.next(m.status);
      stream.next(m.details);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GuideGroupFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::supervision_msgs::GuideGroupFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::supervision_msgs::GuideGroupFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current_node: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.current_node);
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
    s << indent << "details: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.details);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUPERVISION_MSGS_MESSAGE_GUIDEGROUPFEEDBACK_H
