// Generated by gencpp from file supervision_msgs/SupervisionStopped.msg
// DO NOT EDIT!


#ifndef SUPERVISION_MSGS_MESSAGE_SUPERVISIONSTOPPED_H
#define SUPERVISION_MSGS_MESSAGE_SUPERVISIONSTOPPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace supervision_msgs
{
template <class ContainerAllocator>
struct SupervisionStopped_
{
  typedef SupervisionStopped_<ContainerAllocator> Type;

  SupervisionStopped_()
    : is_stopped(false)
    , is_paused(false)  {
    }
  SupervisionStopped_(const ContainerAllocator& _alloc)
    : is_stopped(false)
    , is_paused(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_stopped_type;
  _is_stopped_type is_stopped;

   typedef uint8_t _is_paused_type;
  _is_paused_type is_paused;




  typedef boost::shared_ptr< ::supervision_msgs::SupervisionStopped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::supervision_msgs::SupervisionStopped_<ContainerAllocator> const> ConstPtr;

}; // struct SupervisionStopped_

typedef ::supervision_msgs::SupervisionStopped_<std::allocator<void> > SupervisionStopped;

typedef boost::shared_ptr< ::supervision_msgs::SupervisionStopped > SupervisionStoppedPtr;
typedef boost::shared_ptr< ::supervision_msgs::SupervisionStopped const> SupervisionStoppedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::supervision_msgs::SupervisionStopped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::supervision_msgs::SupervisionStopped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace supervision_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'supervision_msgs': ['/home/zejian/catkin_ws/src/pedsim_ros/visualization/spencer_messages/supervision/supervision_msgs/msg', '/home/zejian/catkin_ws/devel/share/supervision_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::supervision_msgs::SupervisionStopped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::supervision_msgs::SupervisionStopped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::supervision_msgs::SupervisionStopped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::supervision_msgs::SupervisionStopped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::supervision_msgs::SupervisionStopped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::supervision_msgs::SupervisionStopped_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::supervision_msgs::SupervisionStopped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "199f785df4f375bed5b36a8d78b2b2c1";
  }

  static const char* value(const ::supervision_msgs::SupervisionStopped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x199f785df4f375beULL;
  static const uint64_t static_value2 = 0xd5b36a8d78b2b2c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::supervision_msgs::SupervisionStopped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "supervision_msgs/SupervisionStopped";
  }

  static const char* value(const ::supervision_msgs::SupervisionStopped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::supervision_msgs::SupervisionStopped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_stopped\n\
bool is_paused\n\
";
  }

  static const char* value(const ::supervision_msgs::SupervisionStopped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::supervision_msgs::SupervisionStopped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_stopped);
      stream.next(m.is_paused);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SupervisionStopped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::supervision_msgs::SupervisionStopped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::supervision_msgs::SupervisionStopped_<ContainerAllocator>& v)
  {
    s << indent << "is_stopped: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_stopped);
    s << indent << "is_paused: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_paused);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUPERVISION_MSGS_MESSAGE_SUPERVISIONSTOPPED_H
